[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Ensure function paths are properly handled
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# For backward compatibility, also keep the API path
[[redirects]]
  from = "/api/notifications/discord"
  to = "/.netlify/functions/discord-webhook"
  status = 200
  force = true

# For all other routes, serve the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200